### ISSUE TITLE
Built in SSL support

### ISSUE THREAD

**Issue by davorb** [docker-library/owncloud#1]
Is this something that you're planning to add in? If so, do you have a an ETA?

**Comment by yosifkit** [comment]
The short answer is 'no', because it is already available.  There are two options:
- since this is just an apache base, adding on SSL should fit with most guides for that because the [apache2.conf](https://github.com/docker-library/php/blob/master/5.6/apache/apache2.conf#L63-L64) inculdes any configurations you provide (`a2enmod ssl`, `ADD` or mount in certificates, add a `sites-enabled/my-sites-ssl.conf`)
- you could make an nginx or haproxy container in front of this that takes care of the ssl and direct all traffic through there while keeping the owncloud container inaccessible from the outside world

**Comment by sils** [comment]
Would be nice to be able to generate certificates through passing appropriate values as environment variables. Would you accept PRs for such features? (Not from me soon though but maybe at a later point in time...)

**Comment by yosifkit** [comment]
I doubt we would want to have a script that would generate the ssl certs because that would mean also creating a local Certificate Authority. We recommend that should be done with a certificate signing request to an actual authority.

We definitely could use documentation on how to setup a php container with SSL.

**Comment by lazyfrosch** [comment]
@yosifkit agreed

use a proper webserver or haproxy of your liking and your configuration requirements

**Comment by lazyfrosch** [comment]
@yosifkit agreed

use a proper webserver or haproxy of your liking and your configuration requirements

**Comment by lazyfrosch** [comment]
@yosifkit agreeda

use a proper webserver or haproxy of your liking and your configuration requirements

**Comment by tianon** [comment]
Closing given that the original question here is answered.

In the future, these sorts of questions/requests would be more appropriately posted to [the Docker Community Forums](https://forums.docker.com/), [the Docker Community Slack](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker).
