### ISSUE TITLE
Request Entity Too Large

### ISSUE THREAD

**Issue by 0xh0b0** [docker-library/owncloud#19]
When using desktop client (for OSX) big files (>1mb) not uploaded to server.
I see a lot of "Request Entity Too Large" errors in log

**Comment by askhat** [comment]
@brodiaga83 I suppose you somehow dealt with this issue. Would you mind to advice me on it, 'cause I'm experiencing exactly the same?

**Comment by thomasschuiki** [comment]
@ubermonkey I recently had to deal with this error message. Be sure to check out [the docs](https://doc.owncloud.org/server/8.2/admin_manual/configuration_files/big_file_upload_configuration.html). 
Also, are you behind a proxy?
What ultimately resolved my issue was [this](http://www.cyberciti.biz/faq/linux-unix-bsd-nginx-413-request-entity-too-large/) because I am using nginx as a proxy server.
I also had to adjust the [proxy_max_temp_file_size](http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_max_temp_file_size) to allow bigger downloads.

Hope that helps!

**Comment by askhat** [comment]
@thomaseitler turn out it was my own fault. 'Cause I'm using Docker and the issue was actually in incorrect orchestration config. Anyways thank you for suggested reading I find it very useful.
