### ISSUE TITLE
Is it a good idea to automaticly update the docker container?

### ISSUE THREAD

**Issue by SudoHenk** [docker-library/owncloud#70]
I was thinking about maybe automatically updating the OwnCloud docker container once a week, so that I don't have to manually delete/update/start it every time.

Should this be a good idea? The owncloud repo seems to be official, so I guess there is no security risk there, but is it possible that some updates require manual handlings (such as clicking buttons etc.). I basiclly never use the WebGUI and only use the desktop sync ability of owncloud.

_Example of script to update_

```
#!/bin/bash
# Update docker container for owncloud (in crontab once a week).
docker pull owncloud:latest | grep 'Status: Image is up to date for' &> /dev/null
if [ $? == 0 ]; then
        echo "Owncloud is still up to date, no update needed."
else
        echo "Restarting owncloud docker container with owncloud:latest."
        docker stop owncloud
        docker rm owncloud
        docker run -d -p 127.0.0.1:8783:80 -v /var/owncloud:/var/www/html --name="owncloud" owncloud:latest
fi
```

**Comment by yosifkit** [comment]
This won't actually upgrade your OwnCloud source, since the copy from the container to the `/var/www/html` directory only happens when there is no `version.php` (https://github.com/docker-library/owncloud/blob/bfaaed8dc729f4e704b651594d9873e33ef834bd/9.0/apache/docker-entrypoint.sh#L4).  Also, there could possibly be breaking changes from `9` to the next version when `latest` tag changes.

**Comment by SudoHenk** [comment]
Should I remove `version.php` before each docker update to ensure I have the newest version?

**Comment by yosifkit** [comment]
Yes, deleting the file would get the entrypoint script to copy in the owncloud files, but you would probably need to follow the upgrade steps that owncloud recommends. Here is the `8.0` [docs](https://doc.owncloud.org/server/8.0/admin_manual/maintenance/upgrade.html).

**Comment by martingabelmann** [comment]
besides the version.php thingy you could work with prefixes in the containernames, then you just stop the container (instead of deleting it), make a backup of your volume (/var/owncloud) and then start a new one (with another new prefix). This way, in case of a breaking update, you always have a working container... (there should also be a cron that removes the old ones after a few days..)

**Comment by SudoHenk** [comment]
Kay, thanks! I will disable the auto-update function then.
