### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by turingking** [docker-library/owncloud#87]
`docker run -d -p 80:80 -v /share/owncloud/:/var/www/html owncloud
`

`[root@localhost share]# ll
total 0
drwxrwxrwx. 2 root root 6 Mar  7 21:02 owncloud
`

`
f2d7737c2495        owncloud            "/entrypoint.sh apach"   40 seconds ago      Exited (2) 28 seconds ago                       distracted_hodgkin
`
`[root@localhost share]# docker logs --tail 10 f2

tar: ./3rdparty: Cannot mkdir: Permission denied

tar: ./3rdparty/kriswallsmith/assetic/src/Assetic/Filter/StylusFilter.php: Cannot open: No such file or directory

tar: ./3rdparty: Cannot mkdir: Permission denied

tar: ./3rdparty/kriswallsmith/assetic/src/Assetic/Filter/TypeScriptFilter.php: Cannot open: No such file or directory

tar: ./3rdparty: Cannot mkdir: Permission denied
tar: ./3rdparty/kriswallsmith/assetic/src/Assetic/Filter/UglifyCssFilter.php: Cannot open: No such file or directory
tar: ./3rdparty: Cannot mkdir: Permission denied
tar: ./3rdparty/kriswallsmith/assetic/src/Assetic/Filter/UglifyJs2Filter.php: Cannot open: No such file or directory
tar: ./3rdparty: Cannot mkdir: Permission denied
tar: ./3rdparty/kriswallsmith/assetic/src/Assetic/Filter/UglifyJsFilter.php: Cannot open: No such file or directory
`

**Comment by jdrydn** [comment]
Yeah I also get this. Think it's because the UID/GID mismatches against the native FS. Would be nice to manually set a UID/GID, much like [linuxserver.io's containers](https://linuxserver.io), `-e PUID=1000 -e PGID=1000`. Unsure if the underlying PHP image has support for this either.

**Comment by tianon** [comment]
Indeed, using https://github.com/docker-library/wordpress/issues/256 / https://github.com/docker-library/wordpress/pull/249 as a guide, you should be able to use `--user` and/or `APACHE_RUN_USER`/`APACHE_RUN_GROUP` to control the precise user this image runs as.

Since this appears to be an environmental/permissions issue (not something we can fix in the image itself), I'm going to close.  In the future, these sorts of questions/requests would be more appropriately posted to [the Docker Community Forums](https://forums.docker.com/), [the Docker Community Slack](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker).

**Comment by jdrydn** [comment]
> Since this appears to be an environmental/permissions issue (not something we can fix in the image itself)...

My use case isn’t Wordpress, so changing the default user Apache runs as isn’t a fix?

Surely it’s better to support manually setting PUID/PGID so this container can fit into the rest of the network?

**Comment by tianon** [comment]
Your use case is Owncloud, which is based on the same base image as Wordpress (and runs in exactly the same way), which is why I linked to issues on the Wordpress repository which should help.

Using `--user` (a flag directly to `docker run` to change the user the container runs as) or `APACHE_RUN_USER`/`APACHE_RUN_GROUP` is _literally_ "manually setting PUID/PGID", so I'm not sure I understand what you're asking for?

**Comment by tianon** [comment]
Wrote up some official documentation for the generic PHP image in https://github.com/docker-library/docs/pull/1215. :+1:

**Comment by jdrydn** [comment]
My apologies @tianon, that makes sense. Ta 💪
