### ISSUE TITLE
Large files with lets encrypt proxy

### ISSUE THREAD

**Issue by janluak** [docker-library/owncloud#93]
Hey guys,
thank you for your container! Everything works fine from ssl with the proxy container from JrCs to linking to external mysql database besides uploading large files.
I already changed the htaccess and user.ini file but it seems to have no effect.

Do you have any idea where to fix the configuration as well?

thanks a lot!

**Comment by tianon** [comment]
What are you using in front of your ownCloud instance?  NGINX?

Most HTTP reverse proxies I have used impose a limit on the size of uploads at the proxy level as well -- for example, in NGINX you need to set `client_max_body_size` (https://nginx.org/en/docs/http/ngx_http_core_module.html#client_max_body_size).  I'm usually lazy and set that to 0 to disable it entirely, but YMMV.

Since this is more of a configuration question and not an issue with the image that we can fix, I'm going to close it.  In the future, these sorts of questions/requests would be more appropriately posted to [the Docker Community Forums](https://forums.docker.com/), [the Docker Community Slack](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker).  Thanks!
